"""
Codegen artifact writer -- the single place where generated C++ reaches disk.

WHY THIS EXISTS
---------------
Before this module, every ``codegen/`` function returned a string (or a dict)
and *nothing* wrote it out except four private helpers inside
``ui/settings_dialog.py``.  Consequences that this module fixes:

  * A headless run (any preset) produced no codegen at all -- the plugin's
    actual purpose was reachable only by clicking through the GUI.
  * ``generate_all_for_jam`` returns a **dict**; the GUI helper wrote it with
    ``str(result)``, so ``PacketScaffolding_codegen_<build>.h`` contained a
    Python repr with escaped newlines instead of compilable C++.
  * The output directory was hardcoded to ``c:\dumps\codegen_out``.
  * Placeholder text ("// No CMSG opcodes found") counted as content, so empty
    headers were written and reported as success.

Both the GUI batch tasks and ``batch/headless.py`` step 7 now call
``run_all_codegen()`` here, so they cannot drift apart again.
"""

import os
import time

from tc_wow_analyzer.core.utils import msg_info, msg_warn


# Text that generators emit when they have nothing to say. Writing a file whose
# entire body is one of these is worse than writing nothing: it looks like a
# successful artifact.
_PLACEHOLDER_PREFIXES = ("// No ", "// no ")


def codegen_out_dir(session=None):
    """Resolve the codegen output directory.

    Priority: explicit ``codegen_out_dir`` config key -> ``<idb_dir>/codegen_out``
    -> ``<extraction_dir>/codegen_out``.  Never returns an empty string.
    """
    cfg = getattr(session, "cfg", None)
    if cfg is None:
        try:
            from tc_wow_analyzer.core.config import cfg as _cfg
            cfg = _cfg
        except Exception:
            cfg = None

    if cfg is not None:
        explicit = cfg.get("codegen_out_dir")
        if explicit:
            return explicit

    # Next to the IDB -- keeps artifacts with the database they describe.
    try:
        import ida_loader
        idb = ida_loader.get_path(ida_loader.PATH_TYPE_IDB)
        if idb:
            return os.path.join(os.path.dirname(idb), "codegen_out")
    except Exception:
        pass

    if cfg is not None:
        extraction = cfg.extraction_dir
        if extraction:
            return os.path.join(extraction, "codegen_out")

    return os.path.join(os.getcwd(), "codegen_out")


def is_placeholder(text):
    """True if *text* carries no real generated content."""
    if not text or not text.strip():
        return True
    stripped = text.strip()
    if not stripped.startswith(_PLACEHOLDER_PREFIXES):
        return False
    # A placeholder banner followed by real lines is still real content.
    return len([ln for ln in stripped.splitlines() if ln.strip()]) <= 1


def write_artifact(session, filename, body, guard=True, includes=()):
    """Write *body* to ``<codegen_out_dir>/<filename>``.

    Returns the written path, or ``None`` when there was nothing worth writing
    (which is reported, not silently swallowed).
    """
    if is_placeholder(body):
        msg_warn(f"  codegen: {filename} skipped -- generator produced no content")
        return None

    header = []
    if guard:
        header.append("#pragma once")
        header.append("")
    build = build_number(session)
    header.append(f"// Generated by TC WoW Analyzer -- build {build or 'unknown'}")
    header.append(f"// {time.strftime('%Y-%m-%d %H:%M:%S')} -- DO NOT EDIT BY HAND")
    for inc in includes:
        header.append(f"#include {inc}")
    header.append("")

    text = "\n".join(header) + "\n" + body
    if not text.endswith("\n"):
        text += "\n"

    out_dir = codegen_out_dir(session)
    try:
        os.makedirs(out_dir, exist_ok=True)
        path = os.path.join(out_dir, filename)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        msg_info(f"  codegen: wrote {path} ({len(text)} bytes)")
        return path
    except Exception as exc:
        msg_warn(f"  codegen: could not write {filename}: {exc}")
        return None


def build_number(session):
    cfg = getattr(session, "cfg", None)
    if cfg is None:
        return 0
    try:
        return int(cfg.build_number or 0)
    except Exception:
        return 0


# ---------------------------------------------------------------------------
# The four Phase-12 codegen tasks
# ---------------------------------------------------------------------------

def _jam_directions(db):
    """Map jam_type name -> 'CMSG'/'SMSG' using the opcode table.

    The packet generator emits a ``Read()`` for CMSG and a ``Write()`` for
    SMSG.  Calling it without a direction defaulted everything to CMSG, so no
    SMSG type ever got a write method.
    """
    directions = {}
    try:
        rows = db.fetchall(
            "SELECT jam_type, direction FROM opcodes "
            "WHERE jam_type IS NOT NULL AND jam_type != ''")
        for row in rows:
            directions[row["jam_type"]] = row["direction"]
    except Exception as exc:
        msg_warn(f"  codegen: could not resolve JAM directions: {exc}")
    return directions


def _jam_parts_to_cpp(jam_name, parts):
    """Turn the dict from ``generate_all_for_jam`` into a real C++ block.

    Order matters: struct first (it declares the members), then the
    read/write body, then the handler stub.
    """
    if isinstance(parts, str):
        return parts
    if not isinstance(parts, dict):
        return ""
    chunks = []
    for key in ("packet_struct", "read_method", "write_method", "handler_stub"):
        piece = parts.get(key)
        if piece and str(piece).strip():
            chunks.append(str(piece).rstrip())
    if not chunks:
        return ""
    return f"// ---- {jam_name} " + "-" * max(4, 60 - len(jam_name)) + "\n" + \
           "\n\n".join(chunks)


def run_codegen_packets(session):
    """Packet structs + read/write + handler stubs for every JAM type."""
    from tc_wow_analyzer.codegen.packet_scaffolding import generate_all_for_jam
    db = session.db
    rows = db.fetchall(
        "SELECT name FROM jam_types WHERE fields_json IS NOT NULL")
    directions = _jam_directions(db)

    count = 0
    parts = []
    for row in rows:
        name = row["name"]
        direction = directions.get(name, "CMSG")
        block = _jam_parts_to_cpp(name, generate_all_for_jam(session, name, direction))
        if block:
            count += 1
            parts.append(block)

    if parts:
        write_artifact(
            session, f"PacketScaffolding_codegen_{build_number(session)}.h",
            "\n\n".join(parts) + "\n",
            includes=('"WorldPacket.h"', '"Opcodes.h"'))
    return count


def run_codegen_db2(session):
    """DB2 LoadInfo structures for every known table."""
    from tc_wow_analyzer.codegen.db2_stores import generate_loadinfo
    db = session.db
    rows = db.fetchall("SELECT name FROM db2_tables")
    count = 0
    parts = []
    for row in rows:
        code = generate_loadinfo(session, row["name"])
        if code and not is_placeholder(code) and not code.lstrip().startswith("//"):
            count += 1
            parts.append(code)
    if parts:
        write_artifact(
            session, f"DB2LoadInfo_codegen_{build_number(session)}.h",
            "\n\n".join(parts) + "\n",
            includes=('"DB2Structure.h"', '"DB2Metadata.h"'))
    return count


def run_codegen_updatefields(session):
    """UpdateField structures for every object type."""
    from tc_wow_analyzer.codegen.update_fields_gen import generate_all_update_fields
    code = generate_all_update_fields(session)
    if is_placeholder(code):
        return 0
    write_artifact(session,
                   f"UpdateFields_codegen_{build_number(session)}.h", code,
                   includes=('"UpdateField.h"',))
    return max(0, code.count("struct ") - code.count("// struct "))


def run_codegen_opcodes(session):
    """CMSG/SMSG opcode enum entries."""
    from tc_wow_analyzer.codegen.opcode_enums import generate_opcode_enum
    blocks = []
    entries = 0
    for direction in ("CMSG", "SMSG"):
        text = generate_opcode_enum(session, direction)
        if is_placeholder(text):
            msg_warn(f"  codegen: no {direction} opcodes in DB -- nothing to emit")
            continue
        blocks.append(text.rstrip())
        # Count real entries, not newlines: every entry line ends in a comma.
        entries += sum(1 for ln in text.splitlines() if ln.rstrip().endswith(","))
    if not blocks:
        return 0
    write_artifact(session,
                   f"Opcodes_codegen_{build_number(session)}.h",
                   "\n\n".join(blocks) + "\n")
    return entries


CODEGEN_TASKS = (
    ("packets", run_codegen_packets),
    ("db2", run_codegen_db2),
    ("updatefields", run_codegen_updatefields),
    ("opcodes", run_codegen_opcodes),
)


def run_all_codegen(session):
    """Run every Phase-12 codegen task. Returns {task_name: item_count}.

    Each task is isolated: one failing generator must not cost the others their
    output.  Failures are recorded in the failure ledger when a DB is present.
    """
    from tc_wow_analyzer.core import kv_keys

    results = {}
    for name, func in CODEGEN_TASKS:
        try:
            results[name] = func(session)
        except Exception as exc:
            results[name] = -1
            msg_warn(f"  codegen: task {name} failed: {type(exc).__name__}: {exc}")
            db = getattr(session, "db", None)
            if db is not None:
                try:
                    db.record_failure(build_number(session), "codegen", name,
                                      error_type=type(exc).__name__,
                                      error_msg=str(exc)[:500])
                except Exception:
                    pass

    db = getattr(session, "db", None)
    if db is not None:
        try:
            db.kv_set(kv_keys.CODEGEN_LAST_RUN, {
                "build": build_number(session),
                "out_dir": codegen_out_dir(session),
                "results": results,
                "ts": time.time(),
            })
            db.commit()
        except Exception:
            pass
    return results
